### ISSUE TITLE
Can you add a "networking solution" field to the google form?

### ISSUE THREAD

**Issue by fxposter** [hjacobs/kubernetes-on-aws-users#6]
It's interesting what people actually use to make "aws network flat".

**Comment by hjacobs** [comment]
Sounds like a good idea, do you propose any options (flannel, Weave, ..)? We can obviously add the option "Other", but having a predefined list would help people filling it out.

**Comment by fxposter** [comment]
kubenet (ie: AWS-VPC), Flannel (vxlan/udp, host-gw, aws-vpc), Weave, Calico are the most reasonable to include in the list, I believe.

**Comment by hjacobs** [comment]
Closing this as I will keep this repo open, but won't evolve it: a lot of people migrate to Kubernetes on AWS and the added value of this repo is therefore decreasing (if the majority runs Kubernetes on AWS, we don't need to track a list of orgs).
