### ISSUE TITLE
Can you add a "Kubernetes version" field?

### ISSUE THREAD

**Issue by chhuang0123** [hjacobs/kubernetes-on-aws-users#8]
I am also interested "Kubernetes version" on their dev/staging/production env

**Comment by hjacobs** [comment]
@chhuang0123 I want to keep the list "stable", Kubernetes versions change too often (we just upgraded to 1.6.3 for example).

**Comment by chhuang0123** [comment]
@hjacobs: I agree in principle, but...
It is probably useful if we could collect major version on production env.
(We use 1.2.x on staging, 1.4.x on production env and try 1.6.2 on our dev.)
what do you think?

**Comment by hjacobs** [comment]
I will close this as I think Kubernetes versions are updated too frequently to be of any value for a manually filled out form.
