### ISSUE TITLE
Link to Google spreadsheet

### ISSUE THREAD

**Issue by JensRantil** [hjacobs/kubernetes-on-aws-users#9]
I was interested in pulling statistics about "Provisioning". Would have been easier if you also shared a link to the Google Spreadsheet in README. Would that be possible?

**Comment by hjacobs** [comment]
@JensRantil I don't want to share the Google spreadsheet as I believe the submitter's email should stay hidden (at least that's what I would expect as a submitter myself). You can pull all information from the generated `form-responses.json` dump: https://raw.githubusercontent.com/hjacobs/kubernetes-on-aws-users/master/form-responses.json

**Comment by JensRantil** [comment]
Perfect. That works for me.
